name: moneybag
description: "moneybag is a Flutter package project enables merchants to create secure sessions for their customers and seamlessly redirect them to a designated landing page for further transaction processing"
version: 0.0.1
maintainer: Mark O'Sullivan (@yeasin50)
homepage: https://moneybag.com.bd
repository: https://github.com/fitl-com-bd/moneybag_flutter_sdk

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
